### ISSUE TITLE
[macOS] Missing arrows in column headers

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#652]
On macOS, in the column headers NAME, SIZE, DATE etc., the arrows indicating the sort order are not visible. This is true for all LAFs coming with muCommander (FlatLaf, CDE/Motiv, Metal, Nimbus), except Mac OS X.

Another point: It would be good if the name of the active header, i.e. the header which determines the sort order, was printed in **bold face**.

**Comment by ahadas** [comment]
@Andreas0602 I merged the code, could you try it with tomorrow's nightly build? not sure about the bold font of the selected column but maybe it takes some time to get used to it..

**Comment by Andreas0602** [comment]
@ahadas, I've tested the nightly build, and I'm very happy with it. Thank you very much! In my opinion, it's a big step forward from usability point of view.

In the Mac OS X look and feel, the active header is still not bold. Maybe you can fix that. But it's not important to me, since I'm using FlatLaf. By the way, I don't see any good reason why any Mac user would prefer the Mac OS X look & feel over FlatLaf. I'm using FlatLaf already since a few months, and it worked flawlessly. And it looks much better. And it eliminates a number of problems that the Mac OS X look and feel has.

When using FlatLaf, the active header is very, very bold, at least with the light themes. (With the dark themes, it looks more decent). I guess that's why you wrote that you need to get used to it. Maybe you can find a way to make it look a bit less bold. But please do not return to the old behavior. Too much boldness is better than no boldness at all.

All other file managers I've installed on my Mac have the column header names in mixed case, i.e. the first letter of the name is in upper case and the remaining letters are in lower case. muCommander is the only file manager having each letter of the names in UPPER CASE. That does not look good. If you would change it to mixed case, then maybe the bold face in FlatLaf would also look more decent.

**Comment by ahadas** [comment]
@Andreas0602 thanks for the feedback! I'm happy to see you like the changes :)

about the header of the selected column not having bold font on the macOS L&F, yeah, I've noticed that but I don't want to start changing this. I'm checking vaqua that you mentioned on gitter though, if it will be added, it will have the same renderer as the other L&Fs

you're right, the "problem" with the bold font appeared with the light L&F and was less visible with the dark one. I don't think we can control the amount of how bold the font is, the way to change it is by changing the font I guess - and I don't think it is worth it. so yeah, let's keep it that way

please file a different bug on the header titles being in upper case, I'll plan with that and see how it looks when changing it.

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
